#SPDX-License-Identifier: MIT-0
---
# tasks file for docker
- become: true
- block:
    - name: установка зависимостей
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: добавить GPG-ключ для докера
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: добавить репозиторий для докера
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: апгрейд кеша
      apt:
        update_cache: yes

    - name: установка докера
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

    - name: проверить докер-сервис
      service:
        name: docker
        state: started
        enabled: yes

    - name: проверка существования группы "docker"
      ansible.builtin.group:
        name: docker
        state: present

    - name: добавить пользователя в группу
      user:
        name: main_user
        groups: docker
        append: yes

    - name: установка docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: сменить владельца файла, группу и разрешение
      ansible.builtin.file:
        path: /usr/local/bin/docker-compose
        owner: main_user
        group: user