#SPDX-License-Identifier: MIT-0
---
# tasks file for common

- name: set timezone to Europe/Moscow
  timezone:
    name: Europe/Moscow

- name: set new hostname
  ansible.builtin.hostname:
    name: "{{hostname}}"
  become: true

- block:
    - name: создать файл под будущий swap 
      shell: fallocate -l {{swap_size}} /swapfile
      args:
        creates: /swapfile
    
    - name: установить корректные права
      file:
        path: /swapfile
        owner: root
        group: root
        mode: '0600'

    - name: сделать из файла swap-файл
      shell: mkswap /swapfile
      when: ansible_facts.swapfree_mb == 0

    - name: применить swap-файл
      shell: swapon /swapfile
      when: ansible_facts.swapfree_mb == 0

    - name: добавить swap-файл в fstab
      mount:
        name: none
        src: /swapfile
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present