#SPDX-License-Identifier: MIT-0
---
# tasks file for swaptrasher
- name: Удаляю swap-файл и зачищаю fstab
  become: true
  shell: swapoff -a && rm {{ swap_file }} && sed -i '/^\{{ swap_file }}/d' /etc/fstab